# The Site Settings
# v2.0
# https://github.com/cotes2020/jekyll-theme-chirpy
# © 2017-2019 Cotes Chung
# MIT licensed


# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
#--------------------------

title: S41F                          # the main title

tagline: Software & Web Developer, Pentester , Red Teamer WannaBe.  # it will display as the sub-title

description: >-                        # used by seo meta and the atom feed
  software development, HTB, htb,
  web secuirty, code review , red team
  penetration testing.

# Replace with the website url, e.g. 'https://username.github.io'
url: 'https://saifsalah.github.io'

author: Saif Salah                  # change to your full name

avatar: /assets/img/sample/avatar.jpg   # support internet resources

github:
  username: saifsalah             # change to your github username

twitter:
  username: 6675636b6f6666            # change to your twitter username

social:
  name: Saif Salah                  # it will shows as the copyright owner in Footer
  email: null             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/6675636b6f6666      # change to your twitter homepage
    - https://github.com/saifsalag       # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/saif-salah-mukalaf/

google_site_verification: google_meta_tag_verification # change to your verification string

#--------------------------

# if your site type is Project Pages site, change below value to '/projectname'
baseurl: ''

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Asia/Baghdad

google_analytics:
  # Fill with your Google Analytics ID
  id: ''
  # The Google Analytics pageviews switch.

  pv:
    # DO NOT enable it unless you know how to deploy the Google Analytics superProxy.
    enabled: false
    # the next options only valid when `google_analytics.pv` is enabled.
    proxy_url: ''
    proxy_endpoint: ''
    cache: false  # pv data local cache, good for the users from GFW area.

disqus:
  comments: false  # boolean type, the global switch for posts comments.
  shortname: ''    # Fill with your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname


# Prefer color scheme setting, available values:
#
#     dual   - Follow the system prefer color by default, and a toggle will display
#              in the left bottom of Sidebar, which used for switch the theme between dark and light.
#
#     light  - Use the light color scheme
#
#     dark   - Use the dark color scheme
#
theme_mode: dual

# boolean type, global switch for ToC in posts.
toc: true

paginate: 10


